---
config:
  theme: 'base'
  themeVariables:
    primaryColor: '#BB2528'
    primaryTextColor: '#000'
    primaryBorderColor: '#7C0000'
    lineColor: '#F8B229'
    secondaryColor: '#006100'
    tertiaryColor: '#fff'
---

gantt
    title Bibliotech Project Gantt
    dateFormat  DD-MM-YYYY
    axisFormat  %d %b %Y

    section Analysis
    Submit the questionary (2 Days)         :a1, 09-12-2025, 2d
    Analizing the data (1 Day)              :a2, after a1, 1d
    Creating the report (1 Day)             :a3, after a2, 1d

    section Planning 
    Discussion with the team (15/12/2025)   :a4, 15-12-2025, 1d

    section Design
    Logo Creation (5 Days)                  :b0, after a4, 5d
    UI Designing (5 Days)                   :b1, after b0, 5d
    Wireframes (5 Days)                     :b2, after b1, 5d
    Mockups UI and approval (10 Days)       :b3, after b2, 10d

    section Development
    Project Setup (2 Days)                  :c1, after b3, 2d
    Platform Development (24 Days)          :c2, after c1, 24d
    Library Digitalization (18 Days)        :c3, after c2, 18d

    section Testing
    General Testing (4 Days)                :d1, after c3, 4d
    Tests Report (1 Day)                    :d2, after d1, 1d

    section Security
    Security and GDPR Review (3 Days)       :s1, after d2, 3d

    section Report/Presentation
    Final Report (2 Days)                   :e1, after s1, 2d
    Final Presentation (5 Days)             :e2, after e1, 5d