gantt
    title Bibliotech Project Gantt
    dateFormat  DD-MM-YYYY
    axisFormat  %d %b %Y

    section Analysis
    Submit the questionary      :a1, 09-12-2025, 2d
    Analizing the data          :a2, after a1, 1d
    Creating the report         :a3, after a2, 3d

    Discussion with the team    :a4, after a3, 1d

    section Design
    Logo Creation                 :b0, after a4, 5d
    UI Designing                  :b1, after b0, 5d
    Wireframes                    :b2, after b1, 5d
    Mockups UI and approval       :b3, after b2, 5d

    section Development
    Project Setup                 :c1, after b3, 5d
    Platform Development          :c2, after c1, 25d
    Library Digitalization        :c3, after c1, 15d

    section Testing & Security
    Functional Testing            :d1, after c2, 7d
    Security and GDPR Check       :d2, after d1, 5d

    section Reporting
    Final Report                  :e1, after d2, 5d
    Final Presentation            :e2, after e1, 3d
